ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : safety_stop
        timeout : 0.1
        priority: 1
      joystick:
        topic   : teleop
        timeout : 0.1
        priority: 100
      autonomous_control:
        topic   : autonomous_control
        timeout : 0.15
        priority: 50